content:
  - name: wishlist
    label: Wishlist Items
    type: collection
    path: src/content/wishlist
    format: json
    filename: "{primary}.json"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: brand
        label: Brand
        type: string
      - name: description
        label: Description
        type: text
      - name: url
        label: URL
        type: string
      - name: price
        label: Price
        type: string
      - name: priority
        label: Priority
        type: select
        options:
          values: [low, medium, high]
      - name: code
        label: Discount code?
        type: string

  - name: meta
    label: Site Meta
    type: file
    path: src/content/meta.json
    format: json
    fields:
      - name: title
        type: string
        required: true
      - name: subtitle
        type: string
